### PR TITLE
Update team.css

### PR DESCRIPTION
**Pull request by s0hamn**
Solved issue #1 for the team page

### CODE REVIEW

**Comment by AdeshChoudhar** [comment]
LGTM

**Comment by AdeshChoudhar** [comment]
Do not create separate PRs for the same issue. Try solving one issue in a single PR. Make multiple commits to your local branch.

**Comment by s0hamn** [comment]
> Do not create separate PRs for the same issue. Try solving one issue in a single PR. Make multiple commits to your local branch.

Yes sure, I have just started exploring open-source contributions, Git and Github. Thanks for your input.

**Comment by AdeshChoudhar** [comment]
No problem. Congratulations on the first PR to this repository. All the best!

**Pull request merged**
